Handle edgecase

diff --git a/script/bootstrap b/script/bootstrap
--- a/script/bootstrap
+++ b/script/bootstrap
@@ -212,40 +212,55 @@ link_file() {
         skip=true
 
       else
+        while true; do
+          user "File already exists: $dst ($(basename "$src")), what do you want to do?\n\
+          [s]kip, [S]kip all, [o]verwrite, [O]verwrite all, [a]bsorb, [A]bsorb all, [b]ackup, [B]ackup all?"
 
-        user "File already exists: $dst ($(basename "$src")), what do you want to do?\n\
-        [s]kip, [S]kip all, [o]verwrite, [O]verwrite all, [a]bsorb, [A]bsorb all, [b]ackup, [B]ackup all?"
-        read -r -n 1 action
-        echo ''
+          if ! read -r -n 1 action; then
+            echo ''
+            fail "unable to read a response for $dst"
+          fi
 
-        case "$action" in
-        o)
-          overwrite=true
-          ;;
-        O)
-          overwrite_all=true
-          ;;
-        b)
-          backup=true
-          ;;
-        B)
-          backup_all=true
-          ;;
-        a)
-          absorb=true
-          ;;
-        A)
-          absorb_all=true
-          ;;
-        s)
-          skip=true
-          ;;
-        S)
-          skip_all=true
-          ;;
-        *) ;;
+          echo ''
 
-        esac
+          case "$action" in
+          o)
+            overwrite=true
+            break
+            ;;
+          O)
+            overwrite_all=true
+            break
+            ;;
+          b)
+            backup=true
+            break
+            ;;
+          B)
+            backup_all=true
+            break
+            ;;
+          a)
+            absorb=true
+            break
+            ;;
+          A)
+            absorb_all=true
+            break
+            ;;
+          s)
+            skip=true
+            break
+            ;;
+          S)
+            skip_all=true
+            break
+            ;;
+          *)
+            user "invalid choice: $action"
+            ;;
+          esac
+        done
 
       fi
 
