revive atom
Dbeaver

Implement nested symlink and remove hardcoded .

Add python and fixup install script for atom homebrew

Default settings for common macos applications

Add oh-my-zsh

macos-default renaming

Remove node & yarn

Add macos check in script/install.sh

Always run brewfiles

misc fixes

Bug fix

First pass

sudo stuff

make executable

Fixes

Install path fixes

move terminal theme

more attempted fixes

rsync fix

Executable install scripts

Cleanup

Ensure homebrew runs first

Fix homebrew

oh-my-zsh fixes

Plugin updates

oh-my-zsh before dot file link

Add gitconfig

brew updates

Try out antigen

Additional Fixes and cleanup

Migrate missing files from old repo

detailed Library install

Executale installs

Consistent format

Test powerlevel9k

git config fixes

More cleanup

Nano install fix

More Fixes

Cask fixes

Misc bug fixes

Removed unwanted functions and added some

Keep install clean

consistent topic captilization

Things to do

Move macos aliases

Python fixes and backup process change

Firefox

Fixes

More fixes

Fix missing firefox

Added missing git configs

Remove more unneeded git things

Missing some functions

Prompt configurations

Removed chrome references and updated bootstrap

Modified symlink standard to prefix

Fixed 3 bin files

Function migration and README updates

Function cleanup and install bugs squashed

Fix atom install

Homebrew cleanups

Fix new functions

Remove duplicate files

Couple more bug fixes

Update README

Additional bug fixes

README fix

diff --git a/script/bootstrap b/script/bootstrap
--- a/script/bootstrap
+++ b/script/bootstrap
@@ -2,8 +2,9 @@
 #
 # bootstrap installs things.
 
-cd "$(dirname "$0")/.."
-DOTFILES_ROOT=$(pwd -P)
+# cd "$(dirname "$0")/.."
+# DOTFILES_ROOT=$(pwd -P)
+DOTFILES_ROOT=~/.dotfiles
 
 set -e
 
@@ -28,8 +29,15 @@ fail () {
 }
 
 setup_gitconfig () {
-  if ! [ -f git/gitconfig.local.symlink ]
-  then
+  local_git_config="$HOME"/dropbox/config/dotfiles/git/symlink.gitconfig.local
+  if [ -f "$local_git_config" ] && ! [ -f "$HOME"/.gitconfig.local ]; then
+    src=local_git_config
+    dst="$HOME"/.gitconfig.local
+    link_file "$src" "$dst"
+    success "Linked personal $src to $dst"
+  fi
+
+  if ! [ -f git/symlink.gitconfig.local ] && ! [ -f ~/.gitconfig.local ]; then
     info 'setup gitconfig'
 
     git_credential='cache'
@@ -43,7 +51,7 @@ setup_gitconfig () {
     user ' - What is your github author email?'
     read -e git_authoremail
 
-    sed -e "s/AUTHORNAME/$git_authorname/g" -e "s/AUTHOREMAIL/$git_authoremail/g" -e "s/GIT_CREDENTIAL_HELPER/$git_credential/g" git/gitconfig.local.symlink.example > git/gitconfig.local.symlink
+    sed -e "s/AUTHORNAME/$git_authorname/g" -e "s/AUTHOREMAIL/$git_authoremail/g" -e "s/GIT_CREDENTIAL_HELPER/$git_credential/g" git/symlink.gitconfig.local.example > git/symlink.gitconfig.local
 
     success 'gitconfig'
   fi
@@ -108,7 +116,8 @@ link_file () {
 
     if [ "$backup" == "true" ]
     then
-      mv "$dst" "${dst}.backup"
+      mkdir -p "$HOME"/backup-dot-files"$dst"
+      mv "$dst" "$HOME"/backup-dot-files"$dst"
       success "moved $dst to ${dst}.backup"
     fi
 
@@ -120,6 +129,11 @@ link_file () {
 
   if [ "$skip" != "true" ]  # "false" or empty
   then
+    parent=$(dirname "$2")
+    if [ ! -d "$parent" ]
+    then
+      mkdir -p "$parent"
+    fi
     ln -s "$1" "$2"
     success "linked $1 to $2"
   fi
@@ -130,9 +144,13 @@ install_dotfiles () {
 
   local overwrite_all=false backup_all=false skip_all=false
 
-  for src in $(find -H "$DOTFILES_ROOT" -maxdepth 2 -name '*.symlink' -not -path '*.git*')
+  for src in $(find -H "$DOTFILES_ROOT" -maxdepth 2 -name 'symlink-*' -not -path '.git/')
   do
-    dst="$HOME/.$(basename "${src%.*}")"
+    # http://www.gnu.org/software/bash/manual/html_node/Shell-Parameter-Expansion.html
+    # ignores first 7 characters 0-based
+    dst=$(basename "$src")
+    dst="${dst:7}"
+    dst="$HOME/${dst//+//}"
     link_file "$src" "$dst"
   done
 }
@@ -140,17 +158,23 @@ install_dotfiles () {
 setup_gitconfig
 install_dotfiles
 
+# Lets run install files
+if source bin/dot | while read -r data; do info "$data"; done
+then
+  success "dependencies installs"
+else
+  fail "error installing dependencies"
+fi
+
 # If we're on a Mac, let's install and setup homebrew.
 if [ "$(uname -s)" == "Darwin" ]
 then
-  info "installing dependencies"
-  if source bin/dot | while read -r data; do info "$data"; done
-  then
-    success "dependencies installed"
-  else
-    fail "error installing dependencies"
-  fi
+  info "Running on mac"
 fi
 
+info 'changing shell'
+sudo dscl . -create /Users/$USER UserShell /usr/local/bin/zsh
+success "All new sessions will use $SHELL"
+
 echo ''
-echo '  All installed!'
+success '  All installed!'
